spring:
  datasource:
    url: jdbc:h2:~/data/demo
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: jwt

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
